import pyautogui
import time

# Open Opera
pyautogui.press("win")
pyautogui.write(
    "https://mtca2.oraclehospitality.ap-singapore-1.ocs.oraclecloud.com/MINOR/operacloud/faces/opera-cloud-index/OperaCloud"
)
time.sleep(.5)
pyautogui.press("enter")

# In Opera
time.sleep(1)
pyautogui.hotkey("win", "up")
# Zoom out
pyautogui.hotkey("ctrl", "-", interval=.01)
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
pyautogui.hotkey("ctrl", "-")
# Zoom in
pyautogui.hotkey("ctrl", "=")
pyautogui.hotkey("ctrl", "=")
pyautogui.hotkey("ctrl", "=")
time.sleep(3.5)

# To report search
pyautogui.press("tab", presses=5, interval=.01)
pyautogui.press("right", presses=6, interval=.01)
pyautogui.press("down", interval=.01)
pyautogui.press("enter", interval=.01)
time.sleep(3.5)

# # Report: Room Discrepancy
# pyautogui.press("tab", interval=.01)
# pyautogui.write("hkroomdiscrepancy", interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(2.5)
# pyautogui.press("tab", presses=9, interval=.01)
# pyautogui.press("down", presses=2, interval=.01)
# time.sleep(1)
# pyautogui.press("tab", presses=4, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(8.5)
# # Report: Room Discrepancy: Save
# pyautogui.click(600,84, interval=.01)
# pyautogui.press("tab", presses=17, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(1)
# pyautogui.press("tab", presses=6, interval=.01)
# pyautogui.press("enter", interval=.01)
# pyautogui.write(r"C:\Users\dutymanager.vkhl\Documents\Runit\Report\End-day_before")
# pyautogui.press("enter", interval=.01)
# time.sleep(1.5)
# pyautogui.press("tab", presses=4, interval=.01)
# pyautogui.press("down", presses=7, interval=.01) # Report position
# pyautogui.press("enter", interval=.01)
# pyautogui.press("left", interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(.5)
# pyautogui.hotkey("ctrl", "w")
# time.sleep(.5)
# pyautogui.press("tab", presses=29, interval=.01)

# # Report: Guests INH Complimentary and Houseuse
# pyautogui.press("tab", interval=.01)
# pyautogui.write("gi_c_h", interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(2.5)
# pyautogui.press("tab", presses=9, interval=.01)
# pyautogui.press("down", presses=2, interval=.01)
# time.sleep(1)
# pyautogui.press("tab", presses=4, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(8.5)
# # Report: Guests INH Complimentary and Houseuse: Save
# pyautogui.click(600,84, interval=.01)
# pyautogui.press("tab", presses=17, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(1)
# pyautogui.press("tab", presses=6, interval=.01)
# pyautogui.press("enter", interval=.01)
# pyautogui.write(r"C:\Users\dutymanager.vkhl\Documents\Runit\Report\End-day_before")
# pyautogui.press("enter", interval=.01)
# time.sleep(1.5)
# pyautogui.press("tab", presses=4, interval=.01)
# pyautogui.press("down", presses=6, interval=.01) # Report position
# pyautogui.press("enter", interval=.01)
# pyautogui.press("left", interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(.5)
# pyautogui.hotkey("ctrl", "w")
# time.sleep(.5)
# pyautogui.press("tab", presses=29, interval=.01)

# # Report: Guests in house Pseudo room Rate Check
# pyautogui.press("tab", interval=.01)
# pyautogui.write("giratecheck", interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(2.5)
# pyautogui.press("tab", presses=9, interval=.01)
# pyautogui.press("down", presses=2, interval=.01)
# time.sleep(1)
# pyautogui.press("tab", presses=3, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(3.5)
# # Report: Guests in house Pseudo room Rate Check: Config
# pyautogui.click(125,303, interval=.01)
# pyautogui.click(119,523, interval=.5)
# pyautogui.press("tab", presses=7, interval=.01)
# pyautogui.press("space", interval=.01) # Pseudo Rooms
# pyautogui.press("tab", presses=10, interval=.01)
# pyautogui.press("space", interval=.01) # Notes
# time.sleep(.5)
# pyautogui.press("tab", presses=9, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(12.5)
# # Report: Guests in house Pseudo room Rate Check: Save
# pyautogui.click(600,84, interval=.01)
# pyautogui.press("tab", presses=18, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(1)
# pyautogui.press("tab", presses=6, interval=.01)
# pyautogui.press("enter", interval=.01)
# pyautogui.write(r"C:\Users\dutymanager.vkhl\Documents\Runit\Report\End-day_before")
# pyautogui.press("enter", interval=.01)
# time.sleep(1.5)
# pyautogui.press("tab", presses=4, interval=.01)
# pyautogui.press("down", presses=5, interval=.01) # Report position
# pyautogui.press("enter", interval=.01)
# pyautogui.press("left", interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(.5)
# pyautogui.hotkey("ctrl", "w")
# time.sleep(.5)
# pyautogui.press("tab", presses=25, interval=.01)
# pyautogui.press("enter", interval=.01)
# time.sleep(5)
# pyautogui.press("tab", interval=.01)