import pyautogui, time, os, subprocess, pygetwindow, sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

import script_config

pyautogui.FAILSAFE = True

if not os.path.exists(fr"\\{script_config.device_path}"):
     sys.exit()

# Delete files
script_config.remove_file(script_config.daily_report_path)

# Open Opera
subprocess.run(["cmd", "/c", "start", "msedge", f"{script_config.site_OPERA}"])
pygetwindow.getWindowsWithTitle("Opera Cloud")[0].maximize()

# In Opera
script_config.first_OPERA_open()
script_config.zoom_out(10)
script_config.zoom_in(3)
script_config.main_OPERA_menu()

# To report search
pyautogui.press("tab", presses=5, interval=0.01)
pyautogui.press("right", presses=6, interval=0.01)
pyautogui.press("down", interval=0.01)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)
pyautogui.press("tab", interval=0.01)

# VKHL Arrivals
pyautogui.write("Arrivals: Detailed FO", interval=.01)
pyautogui.press("enter", interval=.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=.01)
pyautogui.press("down", presses=2, interval=.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=13, interval=.01)
pyautogui.press("enter", interval=.01)
# VKHL Arrivals: Config
script_config.config_report()
time.sleep(1)
pyautogui.hotkey("ctrl", "a", interval=.01)
pyautogui.write(script_config.td_dd_mm, interval=.01)
pyautogui.press("tab", presses=2, interval=.01)
time.sleep(1)
pyautogui.write(script_config.td_dd_mm, interval=.01)
pyautogui.press("tab", presses=4, interval=.01)
time.sleep(.75)
pyautogui.write(script_config.Room_Type, interval=.01)
pyautogui.press("tab", presses=38, interval=.01)
pyautogui.press("delete", interval=.01)
time.sleep(.5)
pyautogui.press("tab", presses=11, interval=.01)
pyautogui.press("enter", interval=0.01)
# VKHL Arrivals: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "f", interval=.01)
pyautogui.press("tab", presses=5, interval=.01)

VKHL_Arrivals = "4. VKHL Arrivals"

pyautogui.write(VKHL_Arrivals, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)

# VKHL Guests INH (Comp)
script_config.tab_reserve(54)
# VKHL Guests INH (Comp): Config
pyautogui.press("right", interval=0.01)
pyautogui.press("tab", presses=4, interval=0.01)
time.sleep(1)
pyautogui.write(script_config.Room_Class, interval=.01)
pyautogui.press("tab", interval=0.01)
pyautogui.press("delete", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=13, interval=0.01)
pyautogui.press("space", interval=0.01) # Zero Rates Only
time.sleep(.5)
pyautogui.press("tab", presses=2, interval=0.01)
pyautogui.press("space", interval=0.01) # Departures
time.sleep(.5)
pyautogui.press("tab", presses=33, interval=0.01)
pyautogui.press("enter", interval=0.01)
# VKHL Guests INH (Comp): Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

VKHL_Guests_INH_Comp = "6. VKHL Guests INH (Comp)"

pyautogui.write(VKHL_Guests_INH_Comp, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(3)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)
pyautogui.press("tab", interval=0.01)

# VKHL Departures
pyautogui.write("departure_all", interval=.01)
pyautogui.press("enter", interval=0.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=0.01)
pyautogui.press("down", presses=2, interval=0.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=13, interval=0.01)
pyautogui.press("enter", interval=0.01)
# VKHL Departures: Config
script_config.config_report()
time.sleep(1)
pyautogui.press("tab", presses=3, interval=0.01)
time.sleep(.75)
pyautogui.write(script_config.Room_Type, interval=.01)
pyautogui.press("tab", presses=10, interval=.01)
pyautogui.press("space", interval=.01) # Pseudo Rooms
time.sleep(.5)
pyautogui.press("tab", presses=12, interval=.01)
pyautogui.press("space", interval=.01) # Membership Type
time.sleep(.75)
pyautogui.press("tab", interval=.01)
pyautogui.press("space", interval=.01) # Membership Level
time.sleep(.75)
pyautogui.press("tab", presses=13, interval=.01)
pyautogui.press("enter", interval=0.01)
# VKHL Departures: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

VKHL_Departures = "5. VKHL Departures"

pyautogui.write(VKHL_Departures, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(3)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)
pyautogui.press("tab", interval=0.01)

# VKHL Guests INH
pyautogui.write("gibyroom", interval=.01)
pyautogui.press("enter", interval=0.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=0.01)
pyautogui.press("down", presses=2, interval=0.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=13, interval=0.01)
pyautogui.press("enter", interval=0.01)
# VKHL Guests INH: Config
script_config.config_report()
time.sleep(1)
pyautogui.press("tab", interval=.01)
time.sleep(.75)
pyautogui.write(script_config.Room_Type, interval=.01)
pyautogui.press("tab", presses=14, interval=.01)
pyautogui.press("space", interval=.01) # Include Internal Notes
time.sleep(.5)
pyautogui.press("tab", interval=.01)
pyautogui.write("Resv. - GEN", interval=.01)
time.sleep(.5)
pyautogui.press("tab", presses=8, interval=.01)
pyautogui.press("enter", interval=0.01)
# VKHL Guests INH: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

VKHL_Guests_INH = "6. VKHL Guests INH"

pyautogui.write(VKHL_Guests_INH, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)

# VKHL VIP Guests INH
script_config.tab_reserve(19)
# VKHL VIP Guests INH: Config
pyautogui.press("space", interval=.01) # VIP Only
time.sleep(1)
pyautogui.press("tab", presses=20, interval=.01)
pyautogui.press("enter", interval=0.01)
# VKHL VIP Guests INH: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

VKHL_VIP_Guests_INH = "3. VKHL VIP Guests INH"

pyautogui.write(VKHL_VIP_Guests_INH, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(3)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)
pyautogui.press("tab", interval=0.01)

# History and Forecast
pyautogui.write("History and Forecast FO", interval=.01)
pyautogui.press("enter", interval=0.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=0.01)
pyautogui.press("down", presses=2, interval=0.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=13, interval=0.01)
pyautogui.press("enter", interval=0.01)
# History and Forecast: Config
script_config.config_report()
time.sleep(1)
pyautogui.hotkey("ctrl", "a", interval=.01)
pyautogui.write(script_config.date_begin(), interval=.01)
pyautogui.press("tab", interval=.01)
time.sleep(1)
pyautogui.write(script_config.date_end(), interval=.01)
pyautogui.press("tab", presses=20, interval=0.01)
pyautogui.press("enter", interval=0.01)
# History and Forecast: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

History_and_Forecast = "7. History and Forecast"

pyautogui.write(History_and_Forecast, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(.5)

# History and Forecast (AVC)
# History and Forecast (AVC): Config
script_config.tab_reserve(14)
pyautogui.press("space", interval=.01) # Pseudo Rooms
time.sleep(.5)
pyautogui.press("tab", presses=14, interval=.01)
pyautogui.press("enter", interval=0.01)
# History and Forecast (AVC): Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

History_and_Forecast_AVC = "7. History and Forecast (AVC)"

pyautogui.write(History_and_Forecast_AVC, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(3)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)
pyautogui.press("tab", interval=0.01)

# Market Segment Statistics
pyautogui.write("stat_dmy_seg", interval=.01)
pyautogui.press("enter", interval=.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=.01)
pyautogui.press("down", presses=2, interval=.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=13, interval=.01)
pyautogui.press("enter", interval=.01)
# Market Segment Statistics: Config
script_config.config_report()
time.sleep(1)
pyautogui.press("tab", interval=.01)
time.sleep(1)
pyautogui.write(script_config.ytd_dd_mm, interval=.01)
pyautogui.press("tab", presses=17, interval=.01)
pyautogui.press("enter", interval=0.01)
# Market Segment Statistics: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

Market_Segment_Statistics = "10. Market Segment Statistics"

pyautogui.write(Market_Segment_Statistics, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(3)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)
pyautogui.press("tab", interval=0.01)

# AR Credit Limit
pyautogui.write("ar_balance", interval=.01)
pyautogui.press("enter", interval=.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=.01)
pyautogui.press("down", presses=2, interval=.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=14, interval=.01)
pyautogui.press("enter", interval=.01)
# AR Credit Limit: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

AR_Credit_Limit = "16. AR Credit Limit"

pyautogui.write(AR_Credit_Limit, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(.5)
script_config.tab_reserve(13)

# Vacant Rooms
pyautogui.write("Vacant Rooms", interval=.01)
pyautogui.press("enter", interval=.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=.01)
pyautogui.press("down", presses=2, interval=.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=13, interval=.01)
pyautogui.press("enter", interval=.01)
# Vacant Rooms: Config
script_config.config_report()
time.sleep(1)
pyautogui.press("tab", interval=.01)
time.sleep(.75)
pyautogui.write("1H4XK,1H4XT,2U2XKT,2U3XKT", interval=.01)
pyautogui.press("tab", presses=15, interval=.01)
pyautogui.press("enter", interval=0.01)
# Vacant Rooms: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

Vacant_Rooms = "18. Vacant Rooms"

pyautogui.write(Vacant_Rooms, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(3)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)
pyautogui.press("tab", interval=0.01)

# Reservation Cancellations
pyautogui.write("rescancel", interval=.01)
pyautogui.press("enter", interval=.01)
script_config.search_enter_step1()
script_config.search_enter_step2()
time.sleep(.5)
pyautogui.press("tab", presses=9, interval=.01)
pyautogui.press("down", presses=2, interval=.01)
time.sleep(1)
pyautogui.press("right", interval=.01)
pyautogui.press("tab", presses=13, interval=.01)
pyautogui.press("enter", interval=.01)
# Reservation Cancellations: Config
script_config.config_report()
time.sleep(1)
pyautogui.hotkey("ctrl", "a", interval=.01)
pyautogui.write(script_config.ytd_dd_mm, interval=.01)
pyautogui.press("tab", presses=2, interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "a", interval=.01)
pyautogui.write(script_config.ytd_dd_mm, interval=.01)
pyautogui.press("tab", presses=18, interval=.01)
pyautogui.press("enter", interval=.01)
# Reservation Cancellations: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

Reservation_Cancellations = "Reservation Cancellations"

pyautogui.write(Reservation_Cancellations, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(3)
pyautogui.press("enter", interval=0.01)
script_config.search_reports()
time.sleep(1)

# To End of Day Reports
script_config.tab_reserve(7)
pyautogui.press("left", presses=2, interval=.01)
pyautogui.press("down", interval=.01)
time.sleep(.5)
pyautogui.press("down", presses=2, interval=.01)
pyautogui.press("right", presses=1, interval=.01)
pyautogui.press("enter", interval=.01)
time.sleep(2)                             
pyautogui.press("tab", presses=2, interval=.01)

# Guest Ledger Detail
pyautogui.write("gl_led_de", interval=.01)
pyautogui.press("enter", interval=.01)
time.sleep(1.5)
pyautogui.press("tab", presses=8, interval=.01)
pyautogui.press("down", interval=.01)
pyautogui.press("enter", presses=3, interval=1)
# Guest Ledger Detail: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

Guest_Ledger_Detail = "14. Guest Ledger Detail"

pyautogui.write(Guest_Ledger_Detail, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(1)
pyautogui.press("enter", interval=0.01)
time.sleep(1)
script_config.tab_reserve(9)

# Manager Flash
pyautogui.write("manager", interval=.01)
pyautogui.press("enter", interval=.01)
time.sleep(1.5)
pyautogui.press("tab", presses=8, interval=.01)
pyautogui.press("down", interval=.01)
pyautogui.press("enter", presses=3, interval=1)
# Manager Flash: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

Manager_Flash = "8. Manager Flash"

pyautogui.write(Manager_Flash, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(1)
pyautogui.press("enter", interval=0.01)
time.sleep(1)
script_config.tab_reserve(9)

# Trial Balance
pyautogui.write("tb", interval=.01)
pyautogui.press("enter", interval=.01)
time.sleep(1.5)
pyautogui.press("tab", presses=8, interval=.01)
pyautogui.press("down", interval=.01)
time.sleep(.1)
pyautogui.press("enter", presses=3, interval=1)
# Trial Balance: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

Trial_Balance = "9. Trial Balance"

pyautogui.write(Trial_Balance, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)
script_config.tab_reserve(1)
pyautogui.press("enter", interval=0.01)
time.sleep(1)
script_config.tab_reserve(9)

# No Show
pyautogui.write("noshow", interval=.01)
pyautogui.press("enter", interval=.01)
time.sleep(1.5)
pyautogui.press("tab", presses=8, interval=.01)
pyautogui.press("down", interval=.01)
pyautogui.press("enter", presses=3, interval=1)
# No Show: Save
script_config.wait_report()
pyautogui.click(600, 84, interval=0.01)
time.sleep(.5)
pyautogui.hotkey("ctrl", "s", interval=.01)
time.sleep(1)
pyautogui.hotkey("ctrl", "f", interval=.01)
script_config.tab_reserve(2)
time.sleep(0.1)
pyautogui.press("enter", interval=0.01)
pyautogui.write(script_config.daily_report_path)
pyautogui.press("enter", interval=0.01)
time.sleep(.5)
pyautogui.press("tab", presses=6, interval=.01)

No_Show = f"11. No Show on {script_config.ytd_dot_dd_mm}"

pyautogui.write(No_Show, interval=.01)
pyautogui.press("tab", presses=3, interval=.01)
pyautogui.press("enter", interval=0.01)
time.sleep(0.5)                             
pyautogui.hotkey("ctrl", "w")
time.sleep(0.5)

# Open 4. VKHL Arrivals
script_config.print_report_after(VKHL_Arrivals)
time.sleep(.5)
pyautogui.press("end", interval=.01)